$layout(
    title={Dutch HUG Day};
    content={
<h2>Dutch HUG day</h2>
<p>
In honor of the first anniversary of the Dutch Haskell Users Group, we are planning a mini symposium to bring together Haskell and functional programming enthusiasts in the Netherlands and surrounding area.
<p>
The Dutch HUG Day will be held on <strong>Saturday, 24 April</strong>. Please mark that date in your calendar.
<p>
The remaining details are being worked out. In order to help us with this process, we have created a short survey. If you are even remotely considering attending, please take a moment to fill out a form with your name and the activities that interest you.
<ul>
<li><a href=http://spreadsheets.google.com/viewform?formkey=dGVuVTdnZEl0ZDE3MEVweUtRdmlnZGc6MA>Fill in form</a>
</ul>
<p>
Note that this does not commit you to anything. We will only use this information to help plan the event (e.g. determine the number of seats at the location and the types of activities).
}
)$
