$layout(
    title={Dutch HUG};
    content={
<div class="twocolumn leftcolumn">
<h2>Upcoming</h2>
<ul>
<li><strong>Saturday, April 24th</strong> A day long <a href=$approot$DutchHugDay>Dutch HUG event</a> to celebrate the one year anniversary of our user group.
<li><strong>Thursday, May 13th</strong> Scheduled meeting, no details available.
</ul>

<h2>Previously</h2>
<p>
Our last meeting was on Tuesday, March 9th 2010 at the Stairway to Heaven in Utrecht.
<p>
At the January meeting, we had two presentations.
<ul>
<li>Tom Lokhorst and Sebastiaan Visser <a href=http://tom.lokhorst.eu/2010/02/awesomeprelude-presentation-video>presented</a> their <a href=http://github.com/tomlokhorst/AwesomePrelude>AwesomePrelude</a>.
<li>Martijn van Steenbergen talked about serializing monadic computations, and <a href=http://vimeo.com/9375849>presented</a> the <a href=http://code.google.com/p/spaken/source/browse/#svn/trunk>Spaken</a> application.
</ul>
</div>

<div class="twocolumn rightcolumn">
<img src=$staticroot$first-meeting-frontpage.jpg width=370 height=278>
<p>
The Dutch Haskell User Group holds monthly meetings were we socialize and talk about Haskell and functional programming.
<p>
Anyone is welcome to join, from beginners to advanced users. We have a wide range of international members; people using Haskell or functional programming in academia, as a hobby, or for commercial purposes.
<p>
See the <a href="http://groups.google.com/group/dutch-hug">mailing list</a> for up to date information.
</div>
}
)$
