$layout(
    title={Dutch HUG};
    content={
<img src=$staticroot$logo.png class=right>
<h1>Dutch Haskell User Group</h1>
<p>
The Dutch Haskell User Group holds monthly meetings were we socialize and talk about Haskell and functional programming.
<p>
Anyone is welcome to join, from beginners to advanced users. We have a wide range of international members; people using Haskell or functional programming in academia, as a hobby, or for commercial purposes.
<p>
See the <a href="http://haskell.org/haskellwiki/Dutch_HUG">wiki</a> or <a href="http://groups.google.com/group/dutch-hug">mailing list</a> for up to date information.

<h2>Dutch HUG day</h2>
<img src=$staticroot$first-meeting-small.jpg class=right>
<p>
We're currently in the midst of planning a day long Dutch HUG event to celebrate the 1 year anniversary of our user group.
<p>
Proposed activities include:
<ul>
  <li>(Lightening) talks
  <li>Tutorials
  <li>Mini hackathon
  <li>Socializing 
</ul>
<p>
The Dutch HUG day is tentatively scheduled for Saturday, April 24th.
}
)$
