$layout(
    title={Meetings};
    content={
<h2>Meetings</h2>
<p>For the currently scheduled meetings, see the <a href="http://www.google.com/calendar/embed?src=sv7tbnq0qon2sb1k2abb80i66k%40group.calendar.google.com&amp;ctz=Europe/Amsterdam" class='external text' title="http://www.google.com/calendar/embed?src=sv7tbnq0qon2sb1k2abb80i66k@group.calendar.google.com&amp;ctz=Europe/Amsterdam" rel="nofollow">Google calendar</a> or subscribe to the <a href="http://www.google.com/calendar/ical/sv7tbnq0qon2sb1k2abb80i66k%40group.calendar.google.com/public/basic.ics" class='external text' title="http://www.google.com/calendar/ical/sv7tbnq0qon2sb1k2abb80i66k@group.calendar.google.com/public/basic.ics" rel="nofollow">iCal version</a>.
</p><p>Note that this schedule is preliminary, please follow the <a href="http://groups.google.com/group/dutch-hug" class='external text' title="http://groups.google.com/group/dutch-hug" rel="nofollow">mailing list</a> for up to date information.
<p>The next regular meeting is scheduled for <b>Thursday, May 13th</b>. But first is the Dutch HUG day on <b>April 24th</b>!.

<h3>Previous meetings</h3>
<p>The eleventh meeting was in Utrecht, on <b>Tuesday, March 9th</b> at the familiar Stairway to Heaven.
</p><p>On <b>Monday, February 8th</b> we had our second meeting of 2010, again at the <a href="http://www.uu.nl/EN/library/contact/university_library/zaalverhuur/Pages/default.aspx#booth" class='external text' title="http://www.uu.nl/EN/library/contact/university library/zaalverhuur/Pages/default.aspx#booth" rel="nofollow">Booth Hall of the Utrecht University Library</a>. We had two talks:
</p>

<ul><li> Sebastiaan Visser and Tom Lokhorst talked about their Awesome Prelude. [<a href="http://tom.lokhorst.eu/media/presentation-awesomeprelude-dhug-feb-2010.pdf" class='external text' title="http://tom.lokhorst.eu/media/presentation-awesomeprelude-dhug-feb-2010.pdf" rel="nofollow">slides</a>] [<a href="http://github.com/tomlokhorst/AwesomePrelude" class='external text' title="http://github.com/tomlokhorst/AwesomePrelude" rel="nofollow">code</a>] [<a href="http://tom.lokhorst.eu/2010/02/awesomeprelude-presentation-video" class='external text' title="http://tom.lokhorst.eu/2010/02/awesomeprelude-presentation-video" rel="nofollow">video</a>]
</li><li> Martijn van Steenbergen talked about serializing monadic computations in a monadic EDSL to describe compass-and-straightedge constructions. [<a href="http://spaken.googlecode.com/svn/trunk/Spaken.pdf" class='external text' title="http://spaken.googlecode.com/svn/trunk/Spaken.pdf" rel="nofollow">slides</a>] [<a href="http://code.google.com/p/spaken/source/browse/#svn/trunk" class='external text' title="http://code.google.com/p/spaken/source/browse/#svn/trunk" rel="nofollow">code</a>] [<a href="http://vimeo.com/9375849" class='external text' title="http://vimeo.com/9375849" rel="nofollow">video</a>]
</li></ul>

<p>After the talks we had drinks at <a href="http://utrecht.thebasket.nl/" class='external text' title="http://utrecht.thebasket.nl/" rel="nofollow">The Basket</a>.
</p><p>The first meeting of 2010 was on <b>Thursday, January 14th</b> in Utrecht.
</p><p>The eighth and last meeting of 2009 was on <b>Wednesday, December 9th</b>, we met over drinks in Utrecht.
</p><p>The seventh meeting was in Utrecht, on <b>Tuesday, November 10th</b>.
</p><p>The sixth meeting was on <b>Monday, October 12th</b> again in the Utrecht University Library. There were two talks:

</p>
<ul><li> Andres Löh talked about <a href="http://people.cs.uu.nl/andres/lhs2tex/" class='external text' title="http://people.cs.uu.nl/andres/lhs2tex/" rel="nofollow">lhs2TeX</a>, a tool for typesetting Haskell code using LaTeX. [<a href="http://people.cs.uu.nl/andres/lhs2tex-HUG.pdf" class='external text' title="http://people.cs.uu.nl/andres/lhs2tex-HUG.pdf" rel="nofollow">slides</a>]
</li><li> Yaakov Nemoy talked about the status of Haskell packaging in Fedora and how to do it yourself.
</li></ul>
<p>The fifth meeting was on <b>Friday, September 11th</b>, in the Utrecht University Library. There were three talks:
</p>
<ul><li> <a href="http://groups.google.com/group/dutch-hug/msg/1eefa2ea113081ef?hl=en&amp;dmode=source" class='external text' title="http://groups.google.com/group/dutch-hug/msg/1eefa2ea113081ef?hl=en&amp;dmode=source" rel="nofollow">A propositional logic system in Haskell</a> by Thomas B.

</li><li> <a href="http://dreixel.net/research/gpwwh_pres_DHUG09.pdf" class='external text' title="http://dreixel.net/research/gpwwh pres DHUG09.pdf" rel="nofollow">Generic Programming: what, why and how</a> by José Pedro Magalhães (<a href="http://vimeo.com/6715664" class='external text' title="http://vimeo.com/6715664" rel="nofollow">video</a>).
</li><li> <a href="http://splonderzoek.blogspot.com/2009/09/extensibility-and-type-safety-in.html" class='external text' title="http://splonderzoek.blogspot.com/2009/09/extensibility-and-type-safety-in.html" rel="nofollow">Extensibility and type safety in formatting: the design of xformat</a> by Sean Leather (<a href="http://vimeo.com/6864643" class='external text' title="http://vimeo.com/6864643" rel="nofollow">video</a>).
</li></ul>
<p>Afterwards we relocated to <a href="http://utrecht.thebasket.nl/" class='external text' title="http://utrecht.thebasket.nl/" rel="nofollow">The Basket</a> for some well deserved drinks.

</p><p>The fourth meeting was in again Utrecht, on <b>Thursday, August 13th</b>.
</p><p>The third meeting was on <b>Wednesday, July 8th</b>. We <a href="http://www.youtube.com/watch?v=3w3HPDCL34w" class='external text' title="http://www.youtube.com/watch?v=3w3HPDCL34w" rel="nofollow">met over drinks</a> in Utrecht and chatted about Haskell.
</p><p>The second meeting was on <b>Tuesday, June 9th</b> at the top floor of the <a href="http://www.oba.nl/index.cfm/t/Centrale_Bibliotheek/vid/97FCDCDE-E9D2-FB15-B6B840552F884F7D" class='external text' title="http://www.oba.nl/index.cfm/t/Centrale Bibliotheek/vid/97FCDCDE-E9D2-FB15-B6B840552F884F7D" rel="nofollow">library in Amsterdam</a>. We had interesting conversations, and more than one laptop was pulled out of its bag to show off some Haskell code!
</p><p>The first meeting was in Utrecht on <b>Tuesday, May 6th 2009</b>. We met over drinks at the <a href="http://www.stairway.nl/" class='external text' title="http://www.stairway.nl/" rel="nofollow">Stairway to Heaven</a>.
}
)$
